    //mod print;
//mod vars;
//mod types;
//mod print;
//mod strings;
//mod tuples;
//mod arrays;
//mod vectors;
//mod conditionals;
//mod loops; 
mod functions;
//mod pointers;
//mod sorting;
//mod structs;
//mod tuple_structs; 
//person;
//mod std_input;
//mod enums;
//mod cli;
fn main() {
    //print::run();
    //vars::run();
    //types::run();
    //print::run();
    //strings::run();
    //tuples::run();
    //arrays::run(); 
    //arrays::run();
    //vectors::run(); 
    //conditionals::run();
    //loops::run();
    functions::run();
    //pointers::run();
    //sorting::run(); 
    //structs::run(); 
    //tuple_structs::run();
    //person::run();
    //std_input::run(); 
    //enums::run(); 
    //cli::run(); 
}